num_episodes: 1
num_steps: 4000
eval_ep_steps: 3000
task_priority: 9
state: ['f_d', 'position'] # options are 'f_max', 'position', 'position_err', 'position_err_norm', 'f_d', 'f_th', 'u_fb'
reward: ['f_th', 'position'] # options are 'f_d', 'position', 'f_th', 'u_fb'
epsilon: 0.1
test_epsilon: 0.1
feedback_gap: 200

lr: 0.001
lmbd: 0.68

w_force_dev: 0.2
w_pos: 0.1
w_hard_dev_high: 7
w_user_feedback: 0.1
w_user_feedback_dec: 0.1

w_ori: -1
gamma: 0.99
SITL_steps: 5
pos_error_threshold: 0.2
ori_error_threshold: 0.05
variance_threshold: 0.01
window: 800
convergence_checkers: ['var'] # ['var'] # ['task', 'var', 'reward']
